# Generated by Django 3.0.7 on 2020-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last_login'),
        ),
    ]
