# Generated by Django 3.0.7 on 2020-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200613_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='data'),
        ),
    ]
