# Generated by Django 3.0.7 on 2020-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200613_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(verbose_name='Dsata'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
